---
- name: Install Java and Mysql to Amazon Linux 2023
  hosts: ec2
  become: true
  vars:
    ansible_user_dir: /home/ec2-user

  tasks:
    # ---------------------------------------------------
    # OSアップデート
    # ---------------------------------------------------
    #- name: Update all packages and refresh repositories
      #command: dnf update -y
    - name: Perform a full system update
      ansible.builtin.dnf:
        name: "*" # Specifies all packages
        state: latest # Ensures packages are updated to the latest version
        nobest: false # Optional: If set to true, dnf will not try to find the best possible update, potentially leading to partial updates.
        update_cache: true # Optional: Update the dnf cache before performing the update.

    # -------------------------------------------------------------------------------------
    # Install MySQL Community
    # -------------------------------------------------------------------------------------
    - name: Install MySQL Community
      command: >
        dnf -y install https://dev.mysql.com/get/mysql84-community-release-el9-1.noarch.rpm
      #ansible.builtin.dnf:
        #name: 'https://dev.mysql.com/get/mysql84-community-release-el9-1.noarch.rpm'
        #state: present
      #become: yes

    # ---------------------------------------------------
    # Install MySQL クライアント
    # ---------------------------------------------------
    - name: Install MySQL client
      #command: >
        #dnf -y install mysql-community-client
      ansible.builtin.dnf:
        name: mysql-community-client
        state: present

    # ---------------------------------------------------
    # Install Java 21 (Amazon Corretto)
    # ---------------------------------------------------
    - name: Ensure Java 21 is installed
      package:
        name: java-21-amazon-corretto-devel.x86_64
        state: present 

  # -----------------------------------------------------
  # Install Git
  # -----------------------------------------------------
    - name: Ensure Git is installed
      package:
        name: git
        state: present
        update_cache: yes

  # -------------------------------------------------------
  # Git Clone https://github.com/koujienami/aws-study.git
  # -------------------------------------------------------
    - name: git clone
      become: true
      become_user: ec2-user
      ansible.builtin.git:
        repo: https://github.com/koujienami/aws-study.git
        dest: '{{ ansible_user_dir }}/aws-study'